export enum NavigatorConstants {
  MODALS_STACK = 'MODALS_STACK',
  BOTTOM_TAB_STACK = 'BOTTOM_TAB_STACK',
  INITIAL_STACK = 'INITIAL_STACK',
  ERROR_STACK = 'ERROR_STACK',

  INITIAL_SCREEN = 'INITIAL_SCREEN',
  PEOPLE_SCREEN = 'PEOPLE_SCREEN',

  TEST1_SCREEN = 'TEST1_SCREEN',
  TEST2_SCREEN = 'TEST2_SCREEN',
  TEST3_SCREEN = 'TEST3_SCREEN',

  ERROR_SCREEN = 'ERROR_SCREEN',

  TEST1_TAB = 'Тест1',
  TEST2_TAB = 'Тест2',
  TEST3_TAB = 'Тест3',

}
