export enum NavigatorConstants {
  MODALS_STACK = 'MODALS_STACK',
  BOTTOM_TAB_STACK = 'BOTTOM_TAB_STACK',
  INITIAL_STACK = 'INITIAL_STACK',
  ERROR_STACK = 'ERROR_STACK',

  INITIAL_SCREEN = 'INITIAL_SCREEN',

  MAIN_SCREEN = 'MAIN_SCREEN',
  BEST_PLAYERS_SCREEN = 'BEST_PLAYERS_SCREEN',
  NEWS_SCREEN = 'NEWS_SCREEN',
  FAVORITE_SCREEN = 'FAVORITE_SCREEN',
  MATCH_SCREEN = 'MATCH_SCREEN',

  ERROR_SCREEN = 'ERROR_SCREEN',

  TAB_SCREEN_TAB = 'TAB_SCREEN_TAB',

}
